POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0LCJpYXQiOjE3MzgwMDQxMjUsImV4cCI6MTczODA5MDUyNSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.n4Rqk5qGuCIf6KQEzNjGvEomElfFPVhALRR-lzLMN74"
}