
POST http://localhost:5000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0LCJlbWFpbCI6ImRldnp5ekBnbWFpbC5jb20iLCJpYXQiOjE3Mzc5ODk2NTEsImV4cCI6MTczNzk5MzI1MSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.Pg2TuMqSXnE08FMCogVSxeVtcCx1cDfJvpHX4-P3lh0

{
    "firstName": "David",
    "lastName": "Smith",
    "email": "devzy33z@gmail.com",
    "password": "2Password"
}


POST http://localhost:5000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE0LCJlbWFpbCI6ImRldnp5ekBnbWFpbC5jb20iLCJpYXQiOjE3Mzc5Mzc2NjcsImV4cCI6MTczNzk0MTI2NywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.0DMzVNHKw2nhwcXiHONg-2nLSHUQgzYgi2APPK5BhX8
{
    "users": [
    {
        "firstName": "Joe",
        "lastName": "Meatle",
        "email": "devzyr@gmail.com",
        "password": "2Password"
    },
    {
        "firstName": "Fola",
        "lastName": "Stag",
        "email": "devr@gmail.com",
        "password": "2Password"
    }
    ]
}