
POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "Post Title",
    "content": "Post Content",
    "postType": "post",
    "status": "published",
    "slug": "post-title",
    "featuredImage": "https://example.com/image.jpg",
    "publishedOn": "2021-01-01T00:00:00.000Z",
    "tags": ["tag1", "tag2"],
    "schema": "{\r\n    \"@context\": \"https:\/\/schema.org\",\r\n    \"@type\": \"Person\"\r\n  }",
    "metaOptions": [
        {
            "key": "metaKey1",
            "value": "metaValue1"
        },
        {
            "key": "metaKey2",
            "value": "metaValue2"
        }
    ]
}