## Post request for post controller
{{
    const date = new Date();
    exports.startDate = date.toString();
    exports.endDate = date.toString();
}}
GET http://localhost:3000/post/
?limit=1
&page=2                             